[package]
name = "actix-redis"
version = "0.6.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
description = "Redis integration for actix framework"
license = "MIT/Apache-2.0"
readme = "README.md"
keywords = ["web", "redis", "async", "actix", "tokio"]
homepage = "https://github.com/actix/actix-redis"
repository = "https://github.com/actix/actix-redis.git"
documentation = "https://docs.rs/actix-redis/"
categories = ["network-programming", "asynchronous"]
exclude = [".gitignore", ".travis.yml", ".cargo/config", "appveyor.yml"]
edition = "2018"

[lib]
name = "actix_redis"
path = "src/lib.rs"

[badges]
travis-ci = { repository = "actix/actix-redis", branch = "master" }
codecov = { repository = "actix/actix-redis", branch = "master", service = "github" }

[features]
default = ["web"]

# actix-web integration
web = ["actix/http", "actix-service", "actix-utils", "actix-web", "actix-session/cookie-session", "rand", "serde", "serde_json"]

[dependencies]
actix = "0.8.2"

log = "0.4"
backoff = "0.1"
derive_more = "0.14"
futures = "0.1.25"
tokio-io = "0.1"
tokio-codec = "0.1"
tokio-tcp = "0.1"
redis-async = "0.4"
time = "0.1"

# actix web session
actix-web = { version = "1.0.0-rc", optional=true }
actix-utils = { version = "0.4.1", optional=true }
actix-service = { version = "0.4.0", optional=true }
actix-session = { version = "0.1.0", optional=true }
rand = { version="0.6.5", optional=true }
serde = { version="1.0", optional=true }
serde_json = { version="1.0", optional=true }

[dev-dependencies]
env_logger = "0.6"
tokio-timer = "0.2.11"
