version: 2
jobs:
  build:
    docker:
      - image: circleci/rust:1.46
      - image: idein/redis-blackout
      - image: grokzen/redis-cluster
        environment:
          IP: "127.0.0.1"
          SENTINEL: "false"
          STANDALONE: "false"
        ports: '7000-7005:7000-7005'
    steps:
      - checkout
      - run: rustup component add rustfmt
      - run: cargo fmt -- --check
      - run: cargo test -j 1 --verbose
